### ISSUE TITLE
[question] Does this remove the need of patches?

### ISSUE THREAD

**Issue by m-vlad** [mrudat/RaceCompatibilityDialogue#1]
Does this remove the need of using the bruma, AHO etc patches for race compatibility dialogue? Better yet, does this just remove the need of using that esp mod overall?

**Comment by mrudat** [comment]
Presuming that the patches only add compatibility for dialogue added by those mods, yes.

You will still need RaceCompatibility.esm, but you should no longer require RaceCompatibilityDialogue.
